# Generated by Django 3.0.7 on 2020-06-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200627_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='num_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
