# Generated by Django 3.0.7 on 2020-06-28 16:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200628_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CO'),
        ),
    ]
