# Generated by Django 3.0.8 on 2020-07-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200722_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='ciudad_lower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento_lower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
