# Generated by Django 3.0.8 on 2020-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200729_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codunspsc',
            name='id',
        ),
        migrations.AlterField(
            model_name='codunspsc',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
