# Generated by Django 3.0.8 on 2020-07-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200729_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='ciudad_alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
