# Generated by Django 3.0.9 on 2020-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ciudad_ciudad_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codunspsc',
            name='codigo',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
