# Generated by Django 3.1 on 2020-09-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200810_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ciudades',
            field=models.ManyToManyField(to='accounts.Ciudad'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='activ_economica',
            field=models.ManyToManyField(to='accounts.CodUNSPSC'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
