# Generated by Django 3.1 on 2020-10-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='months',
            new_name='days',
        ),
    ]
