# Generated by Django 3.0.8 on 2020-07-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20200722_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_proceso', models.CharField(max_length=50, verbose_name='numero_proceso')),
                ('estado_proceso', models.CharField(max_length=15, verbose_name='estado')),
                ('fuente', models.IntegerField(verbose_name='fuente_informacion')),
                ('entidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='entidad_contratante')),
                ('nit_entidad', models.CharField(blank=True, max_length=9, null=True, verbose_name='nit_entidad')),
                ('objeto_proceso', models.TextField(blank=True, max_length=500, null=True, verbose_name='objeto_proceso')),
                ('detalle_objeto_proceso', models.TextField(blank=True, max_length=1000, null=True, verbose_name='detalle_objeto_proceso')),
                ('valor_proceso', models.CharField(blank=True, max_length=20, null=True, verbose_name='valor_proceso')),
                ('id_tipo_proceso', models.IntegerField(blank=True, null=True, verbose_name='id_tipo_proceso')),
                ('tipo_proceso', models.CharField(blank=True, max_length=150, null=True, verbose_name='tipo_proceso')),
                ('fecha_publicacion', models.CharField(blank=True, max_length=10, null=True, verbose_name='fecha_publicacion')),
                ('plazo_ejecucion_cant', models.IntegerField(blank=True, null=True, verbose_name='plazo_ejecucion_cantidad')),
                ('plazo_ejecucion_und', models.CharField(blank=True, max_length=5, null=True, verbose_name='plazo_ejecucion_unidad')),
                ('fecha_limite', models.CharField(blank=True, max_length=10, null=True, verbose_name='fecha_limite')),
                ('url_proceso', models.URLField(blank=True, null=True, verbose_name='url_proceso')),
                ('cod_unspsc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_principal', to='accounts.CodUNSPSC')),
                ('cod_unspsc_adicionales', models.ManyToManyField(related_name='codigos_adicionales', to='accounts.CodUNSPSC')),
                ('cod_unspsc_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_clase', to='accounts.CodUNSPSC')),
                ('cod_unspsc_familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_familia', to='accounts.CodUNSPSC')),
                ('municipio_ejecucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio_ejecucion', to='accounts.Ciudad', verbose_name='municipio_ejecucion')),
                ('municipio_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio_entidad', to='accounts.Ciudad', verbose_name='municipio_entidad')),
            ],
        ),
    ]
