# Generated by Django 3.0.8 on 2020-07-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='undefined_flag',
            field=models.BooleanField(default=False, verbose_name='undefined'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='nit_entidad',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='nit_entidad'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='url_proceso',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='url_proceso'),
        ),
    ]
