# Generated by Django 3.0.8 on 2020-08-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ciudad_ciudad_alias'),
        ('oportunities', '0003_auto_20200730_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='municipio_ejecucion_adicional',
            field=models.ManyToManyField(related_name='municipio_ejecucion_adicional', to='accounts.Ciudad'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='cod_unspsc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_unspsc', to='accounts.CodUNSPSC'),
        ),
    ]
