# Generated by Django 3.0.9 on 2020-08-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunities', '0004_auto_20200802_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='valor_proceso',
            field=models.DecimalField(decimal_places=2, max_digits=52, null=True, verbose_name='valor_proceso'),
        ),
    ]
