# Generated by Django 3.0.9 on 2020-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunities', '0005_auto_20200811_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_limite'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_publicacion'),
        ),
    ]
